/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "fintrack"
include(
        ":modules:starter:fintrack-starter-test",
        ":modules:starter:fintrack-starter-core",
        ":modules:lib:fintrack-persistence",
        ":modules:lib:fintrack-business",
        ":modules:app:fintrack-webapp",
        ":modules:app:fintrack-webservice",
)